if(!window.__STUDY_APP_LOADED__){
window.__STUDY_APP_LOADED__=true;

let subjects=[];let subjectCache={};let state={view:'home',subject:null,chapter:null,section:null};
const root=document.getElementById('screen'),back=document.getElementById('back'),h=document.getElementById('headTitle'),sub=document.getElementById('headSub'),searchWrap=document.getElementById('searchWrap'),search=document.getElementById('search');
async function fetchJson(file){const urls=[`/data/${file}`,`./data/${file}`];let last;for(const u of urls){try{const r=await fetch(u,{cache:'no-store'});if(r.ok)return await r.json();last=new Error(r.status+' '+u)}catch(e){last=e}}throw last}
function getCW(){try{return JSON.parse(localStorage.getItem('cw'))||[]}catch{return[]}}
function saveCW(data){}
function getChapterProgress(subjectId,chapterId){try{const key=subjectId+'/'+chapterId;const all=JSON.parse(localStorage.getItem('progress'))||{};const p=all[key];if(!p)return{done:0,total:0,pct:'0%'};return{done:p.done,total:p.total,pct:Math.round((p.done/p.total)*100)+'%'}}catch{return{done:0,total:0,pct:'0%'}}}
function renderChapterRow(subjectId,ch,i){const sub=subjects.find(s=>s.id===subjectId)||{};const num=ch.chapterNumber||ch.number||i+1;const title=ch.title||ch.name||'Chapter '+num;const sc=ch.sections?ch.sections.length:(ch.topics?ch.topics.length:0);const p=getChapterProgress(subjectId,ch.id||ch.chapterNumber);return`<button class="row" onclick="go('/${subjectId}/${ch.id||ch.chapterNumber}')"><div class="row-icon">${num}</div><div class="row-body"><b>${escapeHtml(title)}</b><span>${sc} section${sc!==1?'s':''}</span><div class="progress-wrap"><div class="progress-track"><div class="progress-fill" data-width="${p.pct}%" style="background:linear-gradient(90deg,${sub.accent||'#8cb4ff'},${sub.accent2||sub.accent||'#8cb4ff'});width:0%"></div></div><span class="progress-label">${p.done}/${p.total}</span></div></div><span class="row-arrow">→</span></button>`}
function renderCWCard(v){return`<div class="cw-card" onclick="playVideo('${v.subjectId}','${v.chapterId}','${v.sectionId}','${v.videoId}')"><img class="cw-thumb" src="https://img.youtube.com/vi/${v.videoId}/mqdefault.jpg" alt="" loading="lazy"><div class="cw-info"><p class="body-md">${escapeHtml(v.videoTitle)}</p><p class="body-sm">${escapeHtml(v.subjectTitle)} · ${escapeHtml(v.chapterTitle)}</p></div><button class="cw-continue">Continue</button></div>`}
function renderHomeCard(s,i){const icon=subjectIcons[s.id]||'';return`<button class="home-card" onclick="go('/${s.id}')" style="--card-accent:${s.accent};transition-delay:${0.05*(i+1)}s"><div class="home-icon" style="background:linear-gradient(135deg,${s.accent},${s.accent2||s.accent})">${icon}</div><span class="home-title">${escapeHtml(s.title)}</span></button>`}
function transitionTo(renderFn) {
  const el = root;
  el.classList.remove('enter', 'active');
  el.classList.add('exit');
  setTimeout(() => {
    el.innerHTML = '';
    renderFn(el);
    el.classList.remove('exit');
    el.classList.add('enter');
    requestAnimationFrame(() => {
      el.classList.remove('enter');
      el.classList.add('active');
    });
  }, 250);
}
function setTheme(meta){const root=document.documentElement;const defaults={bg:'#070a1a',bg2:'#10143a',bg3:'#2a1558',card:'#11182d',card2:'#17213d',line:'#2a3a66',soft:'#1a2544',accent:'#8cb4ff',accent2:'#a78bfa'};for(const k in defaults){root.style.setProperty('--'+k,meta?.[k]||defaults[k])}}
function setHeader(title,subtitle,canBack=false,showSearch=false){h.textContent=title;sub.textContent=subtitle||'';back.classList.toggle('show',canBack);searchWrap.classList.toggle('show',showSearch);if(!showSearch)search.value=''}
function routeParts(){let p=location.pathname.replace(/^\/site\/?/,'/').replace(/^\/+|\/+$/g,'');return p?p.split('/'):[]}
function go(path){history.pushState(null,'',path);render()}
function metaById(id){return subjects.find(s=>s.id===id)}
async function loadSubject(id){if(subjectCache[id])return subjectCache[id];const m=metaById(id);if(!m)throw new Error('Subject not found');subjectCache[id]=await fetchJson(m.data);return subjectCache[id]}
function countVideos(ch){return ch.videoCount || (ch.videos?ch.videos.length:0) || (ch.sections?ch.sections.reduce((n,s)=>n+s.videos.length,0):0)}
const subjectIcons={math:'<svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 14l4-9 4 9"/><path d="M11 14h2"/><path d="M16 6v8"/><path d="M16 10a2 2 0 0 1 4 0v4"/></svg>',physics:'<svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>',chemistry:'<svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v12"/><path d="M6 12h12"/><ellipse cx="12" cy="12" rx="4" ry="10" transform="rotate(45 12 12)"/><ellipse cx="12" cy="12" rx="4" ry="10" transform="rotate(-45 12 12)"/></svg>',urdu:'<svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.83 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"/></svg>',computer:'<svg viewBox="0 0 24 24" width="28" height="28" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8"/><path d="M12 17v4"/></svg>'};
function home(){state={view:'home'};setTheme({});setHeader('CLASS 9 LECTURES',false);transitionTo(el=>{const cw=getCW();let html='';if(cw.length>0){html+=`<div class="cw-section"><div class="cw-header"><h2>Continue Watching</h2><span class="caption-mono">${cw.length} video${cw.length>1?'s':''}</span></div><div class="cw-row">${cw.map(v=>renderCWCard(v)).join('')}</div></div>`}html+=`<div class="home-grid">${subjects.map((s,i)=>renderHomeCard(s,i)).join('')}</div>`;el.innerHTML=html;requestAnimationFrame(()=>{el.querySelectorAll('.home-card').forEach(c=>c.classList.add('visible'))})})}
function chapterList(subject,meta){state={view:'subject',subject};setTheme(meta);setHeader(subject.title,subject.subtitle,true,false);transitionTo(el=>{const chapters=subject.chapters||[];el.innerHTML=`<div class="row-list">${chapters.map((ch,i)=>renderChapterRow(meta.id,ch,i)).join('')}</div>`;requestAnimationFrame(()=>{el.querySelectorAll('.progress-fill').forEach(p=>{p.style.width=p.dataset.width||'0%'})})})}
function sectionList(subject,chapter,meta){state={view:'chapter',subject,chapter};setTheme(meta);setHeader(chapter.number?'Chapter '+chapter.number:chapter.title,chapter.title,true,false);transitionTo(el=>{const subId=meta.id;const sections=chapter.sections||[];el.innerHTML=`<div class="row-list">${sections.map(sec=>renderSectionRow(subId,chapter,sec)).join('')}</div>`})}
function renderSectionRow(subId,chapter,sec){const vc=sec.videos?sec.videos.length:0;return`<button class="row" onclick="go('/${subId}/${chapter.id}/${sec.id}')"><div class="row-icon">${vc}</div><div class="row-body"><b>${escapeHtml(sec.title)}</b><span>${vc} video${vc!==1?'s':''}</span></div><span class="row-arrow">→</span></button>`}
function videoList(subject,chapter,videos,meta,title,subtitle){state={view:'videos',subject,chapter,videos};setTheme(meta);setHeader(title,subtitle,true,true);transitionTo(el=>{paintVideosInto(el,videos)})}
function paintVideosInto(el,videos){const q=search.value.trim().toLowerCase();const filtered=videos.filter(v=>(v.originalTitle+' '+v.title+' '+(v.subtitle||'')+' '+(v.duration||'')).toLowerCase().includes(q));el.innerHTML=filtered.length?`<div class="videos">${filtered.map(videoCard).join('')}</div>`:`<div class="empty">No videos found.</div>`}
function paintVideos(videos){paintVideosInto(root,videos);requestAnimationFrame(()=>{root.classList.remove('exit','enter');root.classList.add('active')})}
function videoCard(v){return `<article class="video" title="${escapeHtml(v.originalTitle||v.title)}"><button class="thumb" onclick="playVideo('${v.videoId}')" aria-label="Play ${escapeHtml(v.title)}"><img src="${v.thumb}" loading="lazy" alt="Thumbnail for ${escapeHtml(v.title)}">${v.duration?`<span class="thumb-duration">${escapeHtml(v.duration)}</span>`:''}</button><h2>${escapeHtml(v.title)}</h2>${v.subtitle?`<div class="sub">${escapeHtml(v.subtitle)}</div>`:''}</article>`}
function playVideo(...args){const id=args[args.length-1];const o=document.getElementById('playerOverlay'),c=document.getElementById('playerContainer');c.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0&modestbranding=1&iv_load_policy=3&playsinline=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`;o.classList.add('open')}
function closePlayer(){document.getElementById('playerOverlay').classList.remove('open');setTimeout(()=>document.getElementById('playerContainer').innerHTML='',300)}
async function render(){try{const parts=routeParts();if(!parts.length)return home();const sid=parts[0];const meta=metaById(sid);if(!meta)return notFound();const subject=await loadSubject(sid);if(parts.length===1)return chapterList(subject,meta);const ch=subject.chapters.find(c=>c.id===parts[1]);if(!ch)return notFound(meta);if(subject.kind==='exercises'){if(parts.length===2)return sectionList(subject,ch,meta);const sec=ch.sections.find(s=>s.id===parts[2]);if(!sec)return notFound(meta);return videoList(subject,ch,sec.videos,meta,sec.title,`${ch.title} · ${sec.videos.length} videos`)}else{return videoList(subject,ch,ch.videos,meta,ch.number?`Chapter ${ch.number}`:ch.title,`${ch.title} · ${ch.videos.length} videos`)}}catch(e){console.error(e);transitionTo(el=>{el.innerHTML='<div class="empty">Could not load this page. Check that the data files exist.</div>'})}}
function notFound(meta){setTheme(meta||{});setHeader('Not found','This page does not exist',true,false);transitionTo(el=>{el.innerHTML='<div class="empty">Page not found.</div>'})}
function parentPath(){const p=routeParts();if(p.length<=1)return '/';if(p.length===2)return `/${p[0]}`;return `/${p[0]}/${p[1]}`}
back.addEventListener('click',()=>go(parentPath()));search.addEventListener('input',()=>{if(state.view==='videos')paintVideos(state.videos)});window.addEventListener('popstate',render);function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
(async()=>{try{subjects=await fetchJson('subjects.json');render()}catch(e){console.error(e);setHeader('Could not load data','Check /data/subjects.json and deployment root',false,false);transitionTo(el=>{el.innerHTML='<div class="empty">Could not load the site data. If you are opening the file directly, use a local server or deploy the contents of the site folder to Cloudflare Pages.</div>'})}})();

}
