if(!window.__STUDY_APP_LOADED__){
window.__STUDY_APP_LOADED__=true;

let subjects=[];let subjectCache={};let state={view:'home',subject:null,chapter:null,section:null};
const root=document.getElementById('screen'),back=document.getElementById('back'),h=document.getElementById('headTitle'),sub=document.getElementById('headSub'),searchWrap=document.getElementById('searchWrap'),search=document.getElementById('search');
async function fetchJson(file){const urls=[`/data/${file}`,`./data/${file}`];let last;for(const u of urls){try{const r=await fetch(u,{cache:'no-store'});if(r.ok)return await r.json();last=new Error(r.status+' '+u)}catch(e){last=e}}throw last}
function setTheme(meta){const root=document.documentElement;const defaults={bg:'#070a1a',bg2:'#10143a',bg3:'#2a1558',card:'#11182d',card2:'#17213d',line:'#2a3a66',soft:'#1a2544',accent:'#8cb4ff',accent2:'#a78bfa'};for(const k in defaults){root.style.setProperty('--'+k,meta?.[k]||defaults[k])}}
function setHeader(title,subtitle,canBack=false,showSearch=false){h.textContent=title;sub.textContent=subtitle||'';back.classList.toggle('show',canBack);searchWrap.classList.toggle('show',showSearch);if(!showSearch)search.value=''}
function routeParts(){let p=location.pathname.replace(/^\/site\/?/,'/').replace(/^\/+|\/+$/g,'');return p?p.split('/'):[]}
function go(path){history.pushState(null,'',path);render()}
function metaById(id){return subjects.find(s=>s.id===id)}
async function loadSubject(id){if(subjectCache[id])return subjectCache[id];const m=metaById(id);if(!m)throw new Error('Subject not found');subjectCache[id]=await fetchJson(m.data);return subjectCache[id]}
function countVideos(ch){return ch.videoCount || (ch.videos?ch.videos.length:0) || (ch.sections?ch.sections.reduce((n,s)=>n+s.videos.length,0):0)}
function home(){state={view:'home'};setTheme({});setHeader('CLASS 9 LECTURES',false);root.innerHTML=`<div class="grid cards">${subjects.map(s=>`<button class="card" onclick="go('/${s.id}')"><div><div class="emoji">${s.emoji||'📘'}</div><div class="card-kicker">${escapeHtml(s.subtitle)}</div><div class="card-title">${escapeHtml(s.title)}</div></button>`).join('')}</div><div class="foot">Data lives in <code>/data/*.json</code>, so future updates do not require editing the HTML.</div>`}
function chapterList(subject,meta){state={view:'subject',subject};setTheme(meta);setHeader(subject.title,subject.subtitle,true,false);root.innerHTML=`<div class="grid cards">${subject.chapters.map(ch=>`<button class="card" onclick="go('/${subject.id}/${ch.id}')"><div><div class="card-kicker">${ch.number?`Chapter ${ch.number}`:'Extra'}</div><div class="card-title">${escapeHtml(ch.title)}</div></div><div class="card-count">${countVideos(ch)} videos</div></button>`).join('')}</div>`}
function sectionList(subject,chapter,meta){state={view:'chapter',subject,chapter};setTheme(meta);setHeader(chapter.number?`Chapter ${chapter.number}`:chapter.title,chapter.title,true,false);root.innerHTML=`<div class="grid">${chapter.sections.map(sec=>`<button class="row" onclick="go('/${subject.id}/${chapter.id}/${sec.id}')"><div><b>${escapeHtml(sec.title)}</b><span>${sec.videos.length} video${sec.videos.length!==1?'s':''}</span></div><div class="arrow">›</div></button>`).join('')}</div>`}
function videoList(subject,chapter,videos,meta,title,subtitle){state={view:'videos',subject,chapter,videos};setTheme(meta);setHeader(title,subtitle,true,true);paintVideos(videos)}
function paintVideos(videos){const q=search.value.trim().toLowerCase();const filtered=videos.filter(v=>(v.originalTitle+' '+v.title+' '+(v.subtitle||'')+' '+(v.duration||'')).toLowerCase().includes(q));root.innerHTML=filtered.length?`<div class="videos">${filtered.map(videoCard).join('')}</div>`:`<div class="empty">No videos found.</div>`}
function videoCard(v){return `<article class="video" title="${escapeHtml(v.originalTitle||v.title)}"><a class="thumb" href="${v.url}" target="_blank" rel="noopener" aria-label="Open ${escapeHtml(v.title)} on YouTube"><img src="${v.thumb}" loading="lazy" alt="Thumbnail for ${escapeHtml(v.title)}"></a><div class="meta"><span class="pill">#${v.order||v.playlistIndex||''}</span>${v.duration?`<span class="pill">${escapeHtml(v.duration)}</span>`:''}</div><h2>${escapeHtml(v.title)}</h2>${v.subtitle?`<div class="sub">${escapeHtml(v.subtitle)}</div>`:''}<div class="actions"><a class="btn" href="${v.url}" target="_blank" rel="noopener">Open on YouTube</a></div></article>`}
async function render(){try{const parts=routeParts();if(!parts.length)return home();const sid=parts[0];const meta=metaById(sid);if(!meta)return notFound();const subject=await loadSubject(sid);if(parts.length===1)return chapterList(subject,meta);const ch=subject.chapters.find(c=>c.id===parts[1]);if(!ch)return notFound(meta);if(subject.kind==='exercises'){if(parts.length===2)return sectionList(subject,ch,meta);const sec=ch.sections.find(s=>s.id===parts[2]);if(!sec)return notFound(meta);return videoList(subject,ch,sec.videos,meta,sec.title,`${ch.title} · ${sec.videos.length} videos`)}else{return videoList(subject,ch,ch.videos,meta,ch.number?`Chapter ${ch.number}`:ch.title,`${ch.title} · ${ch.videos.length} videos`)}}catch(e){console.error(e);root.innerHTML=`<div class="empty">Could not load this page. Check that the data files exist.</div>`}}
function notFound(meta){setTheme(meta||{});setHeader('Not found','This page does not exist',true,false);root.innerHTML='<div class="empty">Page not found.</div>'}
function parentPath(){const p=routeParts();if(p.length<=1)return '/';if(p.length===2)return `/${p[0]}`;return `/${p[0]}/${p[1]}`}
back.addEventListener('click',()=>go(parentPath()));search.addEventListener('input',()=>{if(state.view==='videos')paintVideos(state.videos)});window.addEventListener('popstate',render);function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
(async()=>{try{subjects=await fetchJson('subjects.json');render()}catch(e){console.error(e);setHeader('Could not load data','Check /data/subjects.json and deployment root',false,false);root.innerHTML='<div class="empty">Could not load the site data. If you are opening the file directly, use a local server or deploy the contents of the site folder to Cloudflare Pages.</div>'}})();

}
